app:
  title: "Crawl4AI API"
  version: "1.0.0"
  host: "0.0.0.0"
  port: 11235
  path_prefix: "/crawl4ai"
  debug: false

security:
  enabled: true
  trusted_hosts: ["localhost", "127.0.0.1"]
  cors_enabled: true
  cors_origins: ["*"]

rate_limiting:
  enabled: true
  default_limit: "100/minute"
  storage_uri: "redis://redis:6379"
  key_func: "client_ip"

caching:
  enabled: true
  redis_url: "redis://redis:6379"
  default_ttl: 3600  # 1 hour

logging:
  level: "INFO"
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  
crawler:
  default_timeout: 30
  max_concurrent_requests: 10
  user_agent: "Crawl4AI/1.0"
  
content_processing:
  max_content_length: 10485760  # 10MB
  allowed_content_types: ["text/html", "application/json", "text/plain"]

health:
  endpoint: "/health"
  enabled: true 