version: '3.8'

services:
  simple-landing:
    build:
      context: .
      dockerfile: Dockerfile.simple-landing
    ports:
      - "7777:8080"
    environment:
      - NODE_ENV=production
      - PORT=8080
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s 