services:
  postgres:
    image: postgres:15
    container_name: n8n_postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: n8n
      POSTGRES_USER: n8n
      POSTGRES_PASSWORD: n8n_secure_password_123
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - n8n_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U n8n -d n8n"]
      interval: 10s
      timeout: 5s
      retries: 5

  n8n:
    image: docker.n8n.io/n8nio/n8n:1.99.1
    container_name: n8n_app
    restart: unless-stopped
    environment:
      DB_TYPE: postgresdb
      DB_POSTGRESDB_HOST: postgres
      DB_POSTGRESDB_PORT: 5432
      DB_POSTGRESDB_DATABASE: n8n
      DB_POSTGRESDB_USER: n8n
      DB_POSTGRESDB_PASSWORD: n8n_secure_password_123
      DB_POSTGRESDB_SCHEMA: public
      N8N_HOST: calculated-reviwer-less-except.trycloudflare.com
      N8N_PROTOCOL: https
      N8N_LISTEN_ADDRESS: 0.0.0.0
      WEBHOOK_URL: https://calculated-reviewer-less-except.trycloudflare.com/
      N8N_AI_ENABLED: "true"
      N8N_ENCRYPTION_KEY: n8n-encryption-key-change-this-to-something-secure-32chars
      N8N_USER_MANAGEMENT_DISABLED: "false"
      N8N_METRICS: "true"
      N8N_LOG_LEVEL: info
      EXECUTIONS_PROCESS: main
      EXECUTIONS_DATA_SAVE_ON_ERROR: all
      EXECUTIONS_DATA_SAVE_ON_SUCCESS: all
      EXECUTIONS_DATA_SAVE_MANUAL_EXECUTIONS: "true"
      N8N_SECURE_COOKIE: "false"
      N8N_EDITOR_BASE_URL: https://calculated-reviewer-less-except.trycloudflare.com/
    volumes:
      - n8n_data:/home/node/.n8n
      - n8n_files:/files
    ports:
      - "5678:5678"
    networks:
      - n8n_network
    depends_on:
      postgres:
        condition: service_healthy

  crawlee:
    build:
      context: .
      dockerfile: Dockerfile.crawlee
    container_name: crawlee_service
    restart: unless-stopped
    environment:
      - NODE_ENV=production
      - PORT=3001
      - LOG_LEVEL=info
    ports:
      - "3001:3001"
    networks:
      - n8n_network
    volumes:
      - crawlee_data:/app/storage
      - /dev/shm:/dev/shm
    deploy:
      resources:
        limits:
          memory: 2G
        reservations:
          memory: 512M

volumes:
  postgres_data:
    driver: local
  n8n_data:
    driver: local
  n8n_files:
    driver: local
  crawlee_data:
    driver: local

networks:
  n8n_network:
    driver: bridge