version: '3.8'

services:
  unified-platform:
    build:
      context: .
      dockerfile: Dockerfile.unified
    ports:
      - "7777:80"      # Main nginx proxy
      - "7778:5678"    # Direct n8n access
      - "7779:11235"   # Direct Crawl4AI access  
      - "7780:8080"    # Direct landing page access
    volumes:
      # Mount logs for debugging
      - ./logs:/var/log/supervisor
      # Mount source code for development (optional)
      # - ./server.js:/app/server.js
      # - ./index.html:/app/index.html
    environment:
      - NODE_ENV=production
      - N8N_HOST=0.0.0.0
      - N8N_PORT=5678
      - PYTHONUNBUFFERED=1
      - DISPLAY=:99
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 120s 