name: multi-app-platform
services:
  # OpenSign Service (using Docker image)
  - name: opensign
    image:
      registry_type: DOCKER_HUB
      registry: opensignlabs/opensign
      tag: latest
    instance_count: 1
    instance_size_slug: basic-s
    routes:
      - path: /opensign
    envs:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        value: ${opensign-db.DATABASE_URL}
      - key: AWS_ACCESS_KEY_ID
        value: ${AWS_ACCESS_KEY_ID}
      - key: AWS_SECRET_ACCESS_KEY
        value: ${AWS_SECRET_ACCESS_KEY}
      - key: AWS_S3_BUCKET
        value: ${AWS_S3_BUCKET}
      - key: PUBLIC_URL
        value: https://${APP_DOMAIN}/opensign
      - key: BASE_PATH
        value: /opensign

  # n8n Service
  - name: n8n
    image:
      registry_type: DOCKER_HUB
      registry: docker.n8n.io/n8nio/n8n
      tag: latest
    instance_count: 1
    instance_size_slug: basic-s
    routes:
      - path: /n8n
    envs:
      - key: N8N_HOST
        value: 0.0.0.0
      - key: N8N_PORT
        value: "8080"
      - key: N8N_PROTOCOL
        value: https
      - key: WEBHOOK_URL
        value: https://${APP_DOMAIN}/n8n/
      - key: N8N_PATH
        value: /n8n
      - key: DB_TYPE
        value: postgresdb
      - key: DB_POSTGRESDB_DATABASE
        value: n8n
      - key: DB_POSTGRESDB_HOST
        value: ${shared-db.HOSTNAME}
      - key: DB_POSTGRESDB_PORT
        value: ${shared-db.PORT}
      - key: DB_POSTGRESDB_USER
        value: ${shared-db.USERNAME}
      - key: DB_POSTGRESDB_PASSWORD
        value: ${shared-db.PASSWORD}
      - key: VUE_APP_URL_BASE_API
        value: https://${APP_DOMAIN}/n8n/

  # Crawl4AI Service
  - name: crawl4ai
    image:
      registry_type: DOCKER_HUB
      registry: unclecode/crawl4ai
      tag: latest
    instance_count: 1
    instance_size_slug: basic-s
    routes:
      - path: /crawl4ai
    envs:
      - key: REDIS_URL
        value: ${shared-redis.REDIS_URL}
      - key: OPENAI_API_KEY
        value: ${OPENAI_API_KEY}
      - key: ANTHROPIC_API_KEY
        value: ${ANTHROPIC_API_KEY}
      - key: LOG_LEVEL
        value: INFO

  # Static Site for Root Path (Landing Page)
  - name: landing
    source_dir: /
    github:
      repo: MLuckyfield/team_ai
      branch: main
    build_command: |
      mkdir -p build
      cat > build/index.html << 'EOF'
      <!DOCTYPE html>
      <html>
      <head>
          <title>Multi-App Platform</title>
          <style>
              body { font-family: Arial, sans-serif; margin: 40px; background: linear-gradient(135deg, #667eea 0%, #764ba2 100%); color: white; min-height: 100vh; }
              .container { max-width: 1200px; margin: 0 auto; padding: 20px; }
              h1 { text-align: center; font-size: 3rem; margin-bottom: 2rem; text-shadow: 2px 2px 4px rgba(0,0,0,0.3); }
              .app-grid { display: grid; grid-template-columns: repeat(auto-fit, minmax(300px, 1fr)); gap: 30px; margin-top: 40px; }
              .app-card { 
                  background: rgba(255,255,255,0.1); 
                  border: 1px solid rgba(255,255,255,0.2); 
                  padding: 30px; 
                  border-radius: 15px; 
                  backdrop-filter: blur(10px);
                  transition: transform 0.3s ease, box-shadow 0.3s ease;
              }
              .app-card:hover { transform: translateY(-5px); box-shadow: 0 10px 25px rgba(0,0,0,0.2); }
              .app-card h2 { color: #fff; margin-bottom: 15px; font-size: 1.5rem; }
              .app-card p { color: rgba(255,255,255,0.8); margin-bottom: 20px; line-height: 1.6; }
              .app-card a { 
                  color: #fff; 
                  text-decoration: none; 
                  background: rgba(255,255,255,0.2);
                  padding: 12px 24px;
                  border-radius: 25px;
                  border: 1px solid rgba(255,255,255,0.3);
                  display: inline-block;
                  font-weight: 500;
                  transition: all 0.3s ease;
              }
              .app-card a:hover { 
                  background: rgba(255,255,255,0.3);
                  transform: scale(1.05);
              }
              .status { text-align: center; margin-top: 40px; color: rgba(255,255,255,0.7); }
          </style>
      </head>
      <body>
          <div class="container">
              <h1>🚀 Multi-Application Platform</h1>
              <div class="app-grid">
                  <div class="app-card">
                      <h2>📝 OpenSign</h2>
                      <p>E-signature platform for document signing and workflow automation</p>
                      <a href="/opensign">Access OpenSign →</a>
                  </div>
                  <div class="app-card">
                      <h2>🔄 n8n</h2>
                      <p>Workflow automation platform for connecting apps and services</p>
                      <a href="/n8n">Access n8n →</a>
                  </div>
                  <div class="app-card">
                      <h2>🕷️ Crawl4AI</h2>
                      <p>AI-powered web crawler service for intelligent data extraction</p>
                      <a href="/crawl4ai">Access Crawl4AI →</a>
                  </div>
              </div>
              <div class="status">
                  <p>All services are running on Digital Ocean App Platform</p>
              </div>
          </div>
      </body>
      </html>
      EOF
    run_command: serve -s build -l 8080
    environment_slug: node-js
    instance_count: 1
    instance_size_slug: basic-xxs
    routes:
      - path: /

# Shared Databases
databases:
  - name: opensign-db
    engine: PG
    size: basic-xs
    num_nodes: 1

  - name: shared-db
    engine: PG
    size: basic-xs
    num_nodes: 1

  - name: shared-redis
    engine: REDIS
    size: basic-xs
    num_nodes: 1

# Environment Variables (to be set in App Platform dashboard)
envs:
  - key: AWS_ACCESS_KEY_ID
    scope: RUN_AND_BUILD_TIME
  - key: AWS_SECRET_ACCESS_KEY
    scope: RUN_AND_BUILD_TIME
  - key: AWS_S3_BUCKET
    scope: RUN_AND_BUILD_TIME
  - key: OPENAI_API_KEY
    scope: RUN_TIME
  - key: ANTHROPIC_API_KEY
    scope: RUN_TIME 