name: n8n-platform
services:
  # n8n Workflow Automation
  - name: n8n
    image:
      registry_type: DOCKER_HUB
      registry: n8nio
      repository: n8n
      tag: "1.75.0"
    instance_count: 1
    instance_size_slug: basic-s
    http_port: 8080
    routes:
      - path: /
    envs:
      - key: N8N_HOST
        value: 0.0.0.0
      - key: N8N_PORT
        value: "8080"
      - key: N8N_PROTOCOL
        value: https
      - key: WEBHOOK_URL
        value: https://${APP_DOMAIN}/
      - key: DB_TYPE
        value: sqlite
      - key: N8N_USER_FOLDER
        value: /home/node/.n8n
      - key: N8N_AI_ENABLED
        value: "true"
      - key: N8N_SECURE_COOKIE
        value: "false"
      - key: N8N_DISABLE_UI
        value: "false"
      - key: GENERIC_TIMEZONE
        value: "UTC"
      - key: OPENAI_API_KEY
        scope: RUN_TIME
      - key: ANTHROPIC_API_KEY
        scope: RUN_TIME
      - key: NODE_ENV
        value: production

# Databases
databases:
  - name: shared-database
    engine: PG
    size: basic-xs
    num_nodes: 1
  - name: opensign-db
    engine: PG
    size: basic-xs
    num_nodes: 1

# Environment Variables
envs:
  - key: NODE_ENV
    scope: RUN_AND_BUILD_TIME
    value: production
  - key: OPENAI_API_KEY
    scope: RUN_TIME
  - key: ANTHROPIC_API_KEY
    scope: RUN_TIME 