name: opensign-app
services:
- name: opensign
  image:
    registry_type: DOCKER_HUB
    repository: opensignlabs/opensign
    tag: latest
  instance_count: 1
  instance_size_slug: basic-s
  http_port: 3000
  routes:
  - path: /
  envs:
  - key: NODE_ENV
    value: production
  - key: DATABASE_URL
    value: ${opensign-db.DATABASE_URL}
  - key: NEXT_PUBLIC_WEBAPP_URL
    value: https://${APP_DOMAIN}

databases:
- name: opensign-db
  engine: PG
  size: basic-xs
  num_nodes: 1 