name: unified-platform
services:
  - name: landing
    github:
      repo: MLuckyfield/team_ai
      branch: main
      deploy_on_push: true
    build_command: npm install
    run_command: npm start
    source_dir: /
    environment_slug: node-js
    instance_count: 1
    instance_size_slug: basic-xxs
    http_port: 8080
routes:
  - path: / 